version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    networks:
      - guitar-tab-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - guitar-tab-network
    depends_on:
      - backend
    restart: unless-stopped

  # 선택사항: Redis (캐싱용)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - guitar-tab-network
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  backend_uploads:
  redis_data:

networks:
  guitar-tab-network:
    driver: bridge